
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 26 11:10:52 CST 2020
//----------------------------------------------------

package tareacompi2;

/** CUP generated class containing symbol constants. */
public class SimbolosT1 {
  /* terminals */
  public static final int error = 1;
  public static final int DIGITO = 2;
  public static final int EOF = 0;
}

